# Generated by Django 5.0.7 on 2024-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_name',
        ),
        migrations.AddField(
            model_name='measurement',
            name='event',
            field=models.CharField(default='', max_length=100, verbose_name='event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
